name: Deploy documentation site to GitHub Pages

on:
  push:
    branches: [trunk]
    paths: [docs/**]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: |
          cd docs
          pnpm install

      - name: Check for cached build
        uses: actions/cache@v3
        id: cache-dist
        with:
          path: dist
          key: |
            docs-${{ runner.os }}-dist-${{ hashFiles(
              'docs/public/**',
              'docs/src/**',
              'docs/**/*.mjs',
              'docs/**/*.json'
            ) }}

      - name: Build project
        if: steps.cache-dist.outputs.cache-hit != 'true'
        run: pnpm build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: jjj.isaaccorbrey.com

    steps:
      # Deploy build to Netlify with commit message
      - name: Deploy to Netlify
        run: |
          COMMIT_MSG=$(echo "${{ github.event.head_commit.message }}" | head -n 1)
          COMMIT_MSG="${COMMIT_MSG//\"/\\\"}"
          npx netlify-cli@17 deploy \
            --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} \
            --site=${{ secrets.NETLIFY_SITE_ID }} \
            --message="$COMMIT_MSG" \
            --dir=docs/dist \
            --prod
